/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/head02.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/head02.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['圖層_01(B004F364-B767-4A43-9762-6AF67843BC82)'].geometry} material={materials['Tire #1']} />
          <mesh geometry={nodes['圖層_01(C1718AF5-D320-47CA-8BBB-F79A859F2849)'].geometry} material={materials['Tire #1']} />
          <mesh geometry={nodes['圖層_01(2D9CC36A-6EA6-48B6-9B1A-251B7127758D)'].geometry} material={materials['Tire #1']} />
          <mesh geometry={nodes['圖層_01(06A8F12E-1B0D-48F2-9553-D48A5636BBAE)'].geometry} material={materials['Tire #1']} />
          <mesh geometry={nodes['圖層_01(7EDC4715-D6B5-4678-B287-9C867DDD7027)'].geometry} material={materials['Tire #1']} />
          <mesh geometry={nodes['圖層_01(88D550CF-252E-4C83-8511-A7E695DD39B7)'].geometry} material={materials['Tire #1']} />
          <mesh geometry={nodes['圖層_01(44F2532B-72C3-4C9F-BAA8-432CE85B0311)'].geometry} material={materials['Tire #1']} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={1022.286} near={150.423} fov={47.053} position={[0.026, 0.19, -0.324]} rotation={[2.944, -0.379, 3.068]} scale={0.001} />
      <PerspectiveCamera makeDefault={false} far={606.931} near={134.167} fov={46.923} position={[0.086, 0.245, -0.653]} rotation={[3.073, -0.125, 3.133]} scale={0.001} />
      <OrthographicCamera makeDefault={false} far={18135.346} near={17831.67} position={[0.154, 18.01, -0.196]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 10, 0.1]} />
      <OrthographicCamera makeDefault={false} far={662.888} near={302.316} position={[0.187, 0.308, 0.216]} scale={[0.1, 10, 0.1]} />
      <OrthographicCamera makeDefault={false} far={2118.881} near={1357.391} position={[1.852, 0.306, -0.11]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 10, 0.1]} />
      <PerspectiveCamera makeDefault={false} far={1383.284} near={818.618} fov={47.053} position={[0.444, 0.099, 1.064]} rotation={[0.181, 0.288, -0.052]} scale={0.001} />
      <PerspectiveCamera makeDefault={false} far={1610.419} near={750.07} fov={47.053} position={[1.187, 0.12, 0.504]} rotation={[0.39, 1.207, -0.367]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/head02.glb')
